/**
 * Photo registry, GENERATED by scripts/process-photos.py.
 * Every file in /public/photos is a real Petty Shine job photo,
 * re-encoded to AVIF + WebP at 640 / 1024 / 1600 / 2200 widths.
 */

export interface PhotoEntry {
  w: number;
  h: number;
  sizes: number[];
  alt: string;
}

export const PHOTOS = {
  "marine-boat-trailer": { w: 1241, h: 913, sizes: [640, 1024], alt: "Center console fishing boat on a trailer after a marine detail at Petty Shine in Randleman, North Carolina" },
  "coating-challenger-hellcat": { w: 1440, h: 1081, sizes: [640, 1024], alt: "Blue Dodge Challenger SRT Hellcat Widebody after paint correction and ceramic coating at Petty Shine" },
  "ppf-mclaren-gt": { w: 960, h: 720, sizes: [640], alt: "Red McLaren GT inside the Petty Shine shop in Randleman, North Carolina" },
  "coating-corvette-z06": { w: 1080, h: 848, sizes: [640, 1024], alt: "Black Chevrolet Corvette Z06 after ceramic coating at Petty Shine" },
  "coating-challenger-demon": { w: 1440, h: 1080, sizes: [640, 1024], alt: "Blue Dodge Challenger SRT Widebody outside the Petty Shine shop after a full detail" },
  "interior-bmw-x5m": { w: 1440, h: 1143, sizes: [640, 1024], alt: "Tan leather interior of a BMW X5 M after an interior detail at Petty Shine" },
  "interior-bmw-door": { w: 1440, h: 1143, sizes: [640, 1024], alt: "BMW door panel and front seat after interior detailing and leather conditioning" },
  "interior-mustang-dash": { w: 1440, h: 1082, sizes: [640, 1024], alt: "Ford Mustang dashboard and steering wheel after an interior detail at Petty Shine" },
  "detail-mustang-65": { w: 1440, h: 1080, sizes: [640, 1024], alt: "White 1965 Ford Mustang under the Petty Shine banner in the Randleman shop" },
  "interior-mustang-65": { w: 1440, h: 1082, sizes: [640, 1024], alt: "Classic Ford Mustang interior and steering wheel after a full interior detail" },
  "wash-f250-foam": { w: 1440, h: 1080, sizes: [640, 1024], alt: "Lifted white Ford F-250 Super Duty covered in foam during the wash stage at Petty Shine" },
  "wash-porsche-911": { w: 1536, h: 1536, sizes: [640, 1024], alt: "Red Porsche 911 being washed inside the Petty Shine shop in Randleman" },
  "detail-raptor": { w: 1440, h: 1083, sizes: [640, 1024], alt: "Red Ford F-150 Raptor after a full detail at Petty Shine" },
  "wash-huracan-foam": { w: 1284, h: 1011, sizes: [640, 1024], alt: "Lamborghini Huracan covered in foam during a decontamination wash at Petty Shine" },
  "coating-huracan": { w: 1920, h: 1440, sizes: [640, 1024, 1600], alt: "Blue Lamborghini Huracan under the Petty Shine banner after ceramic coating" },
  "ppf-jeep-install": { w: 1536, h: 2048, sizes: [640, 1024], alt: "Paint protection film being installed on the hood of a black Jeep at Petty Shine" },
  "detail-jeep-orange": { w: 1920, h: 1440, sizes: [640, 1024, 1600], alt: "Orange Jeep on 37s inside the Petty Shine shop after a full detail" },
  "detail-f250-black": { w: 1920, h: 1440, sizes: [640, 1024, 1600], alt: "Black Ford F-250 Super Duty inside the Petty Shine shop after paint correction" },
  "coating-corvette-c8": { w: 1920, h: 1440, sizes: [640, 1024, 1600], alt: "Rapid Blue Chevrolet Corvette C8 after ceramic coating at Petty Shine in Randleman" },
  "coating-corvette-c8-side": { w: 960, h: 720, sizes: [640], alt: "Side profile of a Rapid Blue Corvette C8 after paint correction and ceramic coating" },
  "correction-reflection": { w: 960, h: 720, sizes: [640], alt: "Mirror reflections in black paint after a full paint correction at Petty Shine" },
  "detail-jeep-teal": { w: 1920, h: 1440, sizes: [640, 1024, 1600], alt: "Teal Jeep Wrangler Rubicon outside the Petty Shine shop after a detail" },
  "coating-g-wagon": { w: 1920, h: 1440, sizes: [640, 1024, 1600], alt: "Black Mercedes-Benz G-Class inside the Petty Shine shop after ceramic coating" },
  "coating-supra": { w: 960, h: 720, sizes: [640], alt: "White Toyota Supra under the Petty Shine banner after paint correction" },
  "correction-red-panel": { w: 1440, h: 1080, sizes: [640, 1024], alt: "Deep gloss in red paint after machine polishing at Petty Shine" },
  "coating-corvette-c7": { w: 1440, h: 1083, sizes: [640, 1024], alt: "Black Chevrolet Corvette Grand Sport inside the Petty Shine shop after ceramic coating" },
  "ppf-install-closeup": { w: 1440, h: 1197, sizes: [640, 1024], alt: "Paint protection film being squeegeed onto a black painted panel at Petty Shine" },
  "detail-mustang-red": { w: 1707, h: 1280, sizes: [640, 1024, 1600], alt: "Red Ford Mustang GT under the Petty Shine banner in the Randleman shop" },
  "wheels-mustang": { w: 1920, h: 1438, sizes: [640, 1024, 1600], alt: "Black Ford Mustang with its wheels removed for a full wheel-off detail at Petty Shine" },
} as const satisfies Record<string, PhotoEntry>;

export type PhotoId = keyof typeof PHOTOS;

/** Largest rendition available for a photo. */
export function photoSrc(id: PhotoId, width?: number): string {
  /* `as const` narrows sizes to a literal tuple, so Array.includes types its
     own argument to those literals and rejects a plain number. Widen once,
     here, rather than casting at every call site. */
  const sizes: readonly number[] = PHOTOS[id].sizes;
  const w = width && sizes.includes(width) ? width : sizes[sizes.length - 1];
  return `/photos/${id}-${w}.webp`;
}

/** srcset across every rendition on disk. */
export function photoSrcSet(id: PhotoId): string {
  return PHOTOS[id].sizes.map((w) => `/photos/${id}-${w}.webp ${w}w`).join(", ");
}
