#!/usr/bin/env python3
"""
Rebuild the photo renditions in public/photos from source images.

Source photos live in scripts/source/ (not committed , they are the shop's
originals, pulled from the old pettyshine.com site or supplied by Judson). Each entry
in MAP names one source file, the slug the site refers to it by, and its
alt text.

Every photo is emitted as AVIF + WebP at 640/1024/1600/2200 widths, and
src/lib/photos.ts is regenerated with the intrinsic dimensions so pages
never shift while images load.

    python3 scripts/process-photos.py
"""

from PIL import Image, ImageOps
import json
import os

SRC = os.path.join(os.path.dirname(__file__), "source")
OUT = os.path.join(os.path.dirname(__file__), "..", "public", "photos")
LIB = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "photos.ts")
WIDTHS = [640, 1024, 1600, 2200]
WEBP_Q = 80
AVIF_Q = 58

# slug -> (source filename, alt text)
MAP = {}
manifest_path = os.path.join(OUT, "manifest.json")
if os.path.exists(manifest_path):
    # Reuse the existing alt text so descriptions survive a re-run.
    for slug, entry in json.load(open(manifest_path)).items():
        MAP[slug] = (entry.get("src", f"{slug}.jpg"), entry["alt"])


def main():
    os.makedirs(OUT, exist_ok=True)
    manifest = {}

    for slug, (filename, alt) in MAP.items():
        path = os.path.join(SRC, filename)
        if not os.path.exists(path):
            print(f"  skip {slug}: {filename} not found")
            continue

        im = ImageOps.exif_transpose(Image.open(path)).convert("RGB")
        w, h = im.size
        sizes = []
        for tw in WIDTHS:
            if tw > w and sizes:
                continue
            th = round(h * tw / w)
            r = im.resize((tw, th), Image.LANCZOS)
            r.save(f"{OUT}/{slug}-{tw}.webp", "WEBP", quality=WEBP_Q, method=6)
            r.save(f"{OUT}/{slug}-{tw}.avif", "AVIF", quality=AVIF_Q, speed=6)
            sizes.append(tw)

        manifest[slug] = {"src": filename, "alt": alt, "w": w, "h": h, "sizes": sizes}
        print(f"  {slug}: {w}x{h} -> {sizes}")

    json.dump(manifest, open(manifest_path, "w"), indent=1)
    write_registry(manifest)
    print(f"{len(manifest)} photos processed")


def write_registry(manifest):
    lines = [
        "/**",
        " * Photo registry, GENERATED by scripts/process-photos.py.",
        " * Every file in /public/photos is a real Petty Shine job photo,",
        " * re-encoded to AVIF + WebP at 640 / 1024 / 1600 / 2200 widths.",
        " */",
        "",
        "export interface PhotoEntry {",
        "  w: number;",
        "  h: number;",
        "  sizes: number[];",
        "  alt: string;",
        "}",
        "",
        "export const PHOTOS = {",
    ]
    for slug, e in manifest.items():
        alt = e["alt"].replace('"', '\\"')
        lines.append(
            f'  "{slug}": {{ w: {e["w"]}, h: {e["h"]}, '
            f'sizes: {json.dumps(e["sizes"])}, alt: "{alt}" }},'
        )
    lines += [
        "} as const satisfies Record<string, PhotoEntry>;",
        "",
        "export type PhotoId = keyof typeof PHOTOS;",
        "",
        "/** Largest rendition available for a photo. */",
        "export function photoSrc(id: PhotoId, width?: number): string {",
        "  const p = PHOTOS[id];",
        "  const w = width && p.sizes.includes(width) ? width : p.sizes[p.sizes.length - 1];",
        "  return `/photos/${id}-${w}.webp`;",
        "}",
        "",
        "/** srcset across every rendition on disk. */",
        "export function photoSrcSet(id: PhotoId): string {",
        '  return PHOTOS[id].sizes.map((w) => `/photos/${id}-${w}.webp ${w}w`).join(", ");',
        "}",
        "",
    ]
    open(LIB, "w").write("\n".join(lines))


if __name__ == "__main__":
    main()
